### ISSUE TITLE
Redraw of mandatory items loses checkbox state

### ISSUE THREAD

**Issue by natcyn** [BlueM/Pashua-Bindings#1]
Greetings- If the user tries to close a dialog with an empty mandatory item the state of checkboxes is lost.  Other elements retain their state, as expected.  I can send a concise bug case if you wish.

Thanks,
Nat Goodman
natg@shore.net

**Comment by BlueM** [comment]
Thanks for reporting – this is [fixed in version 0.10.2](https://www.bluem.net/en/news-and-beyond/).

For the record: this is an issue which does not belong to this repository, so it should not have been reported here. Issues in Pashua itself should be reported by mail, as there is no public issue tracker for Pashua.

**Comment by natcyn** [comment]
Thanks for fixing the bug so promptly! If future problems arise, I will mail you directly as you request. 

Best,

## Nat

**Comment by natcyn** [comment]
Hello again

Another small bug.  In 0.10.2, the combobox display seems a little askew: the vertical position of the visible item is a little low.  The attached screenshot is made from a config string that is very slightly adapted from your documentation.  The combobox portion of the config is

combo.type = combobox
combo.label = My combobox label
combo.default = Gromit
combo.option = Wallace
combo.option = Harold
combo.option = Maude
combo.width = 220
combo.tooltip = Choose from the list or enter another name

Thanks,
Nat

**Comment by BlueM** [comment]
Some remarks:
- Again: this repository is not the right place for posting Pashua issues
- If it was, then it should have been a _new_ issue, as it is not related to the problem you described in your initial issue.
- There is no attached screenshot
