### ISSUE TITLE
space character in Info.plist causing error when using/launching Doubleclickable version with 10.11.x...

### ISSUE THREAD

**Issue by hoondi** [BlueM/Pashua-Bindings#2]
Line 14 of Info.plist within provided bundle:
<string>Example Application</string>

In the above example, "Example Application" will cause error due to the space character, and results in a finder dialog box: The Application "Example Application.app" can't be opened. 

Removing the space rectifies.
Can still have spaces in actual name of bundle though .e.g. Example Application.app

**Comment by BlueM** [comment]
No, this does not cause an error. As the Pashua distribution does not contain the string “Example Application” anywhere, I guess you copied, renamed and modified the “Doubleclickable Example” and somehow produced an error – for example, by not renaming `Contents/MacOS/Doubleclickable Example` accordingly.

For the record: this is an issue which does not belong to this repository, so it should not have been reported here. Issues in Pashua itself should be reported by mail, as there is no public issue tracker for Pashua.
