### ISSUE TITLE
Any way to manually close the window?

### ISSUE THREAD

**Issue by styks1111** [BlueM/Pashua-Bindings#4]
While my script is doing something in the background, I would like to show a waiting dialog, and then close that dialog once the process has completed. Is this possible?

Or even better would be a way to dynamically update the dialog with new content?

Thanks!

**Comment by BlueM** [comment]
Pashua is limited to reading a dialog configuration/description and returning the result of the dialog. Nothing else. (Basically, inter-process communication between the calling process and the Pashua process is feasible, but given the dated codebase, there are bigger problems to solve.)

However, if you are not interested in the dialog’s result, you could simply `kill` the Pashua process from your script when it has done its background processing. For getting Pashua’s process ID, you could do something like …

    ps aux | grep Pashua | grep -v grep | awk '{print $2}'
