### ISSUE TITLE
Pashua + Python3 Impossible to add two fields of the same type

### ISSUE THREAD

**Issue by ghost** [BlueM/Pashua-Bindings#5]
Hi;

I've noticed that it is impossible to create two textfields, or two openbrowser, or any other two identical objects. When I do that, he just create the last. I even tried doing this on the example.py itself with similar results.

**Comment by BlueM** [comment]
See https://www.bluem.net/pashua-docs-latest.html#faq.multipleelements

**Comment by ghost** [comment]
Nice, thank you. I oversaw that when reading the documentation (the **chk[1],[2],[3]**...)
